# Generated by Django 3.0.5 on 2020-04-09 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200408_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profil',
        ),
    ]
