# Generated by Django 3.0.5 on 2020-04-21 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200421_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Game'),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='score1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='score2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='team1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='app.Team'),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='structure',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
